root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  entrypoint = ["./tmp/main.exe"]
  delay = 200
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
  time = true
