[tool.air]
root = "."
tmp_dir = "tmp"

[tool.air.build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  entrypoint = ["./tmp/main.exe"]
  delay = 200
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "node_modules"]

[tool.air.log]
  time = true
